<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="libphonenumber-csharp" Version="9.0.20" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShoeEcommerce.Domain\ShoeEcommerce.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Models\" />
    <Folder Include="Common\Behaviors\" />
    <Folder Include="Features\Authentication\Queries\" />
  </ItemGroup>

</Project>
