using ShoeEcommerce.Application.Common.Exceptions;
using ShoeEcommerce.Application.Common.Helpers;
using ShoeEcommerce.Application.Common.Interfaces.Repositories;
using ShoeEcommerce.Application.Common.Interfaces.Services;
using ShoeEcommerce.Application.Features.Authentication.DTOs;
using ShoeEcommerce.Domain.Entities;

namespace ShoeEcommerce.Application.Features.Authentication.Commands.Register;
public class RegisterCommandHandler
{
    private readonly IUserRepository _userRepository;
    private readonly IPasswordHasher _passwordHasher;
    private readonly ITokenService _tokenService;
    private readonly IRefreshTokenRepository _refreshTokenRepository;
    private readonly IRoleRepository _roleRepository;

    public RegisterCommandHandler(
        IUserRepository userRepository,
        IPasswordHasher passwordHasher,
        ITokenService tokenService,
        IRefreshTokenRepository refreshTokenRepository,
        IRoleRepository roleRepository)
    {
        _userRepository = userRepository;
        _passwordHasher = passwordHasher;
        _tokenService = tokenService;
        _refreshTokenRepository = refreshTokenRepository;
        _roleRepository = roleRepository;
    }


    public async Task<AuthResponse> Handle(RegisterCommand command)
    {
        var normalizedEmail = command.Email.ToUpperInvariant();
        if (await _userRepository.EmailExistsAsync(normalizedEmail))
        {
            throw new ConflictException("Email address is already registered");
        }

        if (!string.IsNullOrWhiteSpace(command.Username))
        {
            var normalizedUsername = command.Username.ToUpperInvariant();
            if (await _userRepository.UsernameExistsAsync(normalizedUsername))
            {
                throw new ConflictException("Username is already taken");
            }
        }

        string? normalizedPhone = null;
        if (!string.IsNullOrWhiteSpace(command.PhoneNumber))
        {
            normalizedPhone = command.PhoneNumber.StartsWith("+")
                ? PhoneNumberHelper.Normalize(command.PhoneNumber)
                : PhoneNumberHelper.Normalize(command.PhoneNumber, command.PhoneCountryCode);

            if (normalizedPhone == null)
            {
                throw new ValidationException("Invalid phone number format");
            }

            if (await _userRepository.PhoneExistsAsync(normalizedPhone))
            {
                throw new ConflictException("Phone number is already registered");
            }
        }

        var passwordHash = _passwordHasher.HashPassword(command.Password);

        var user = new User
        {
            Email = command.Email,
            NormalizedEmail = normalizedEmail,
            EmailConfirmed = false,

            FullName = command.FullName,

            Username = command.Username,
            NormalizedUsername = string.IsNullOrWhiteSpace(command.Username)
                ? null
                : command.Username.ToUpperInvariant(),

            PhoneNumber = command.PhoneNumber,
            NormalizedPhoneNumber = normalizedPhone,
            PhoneNumberConfirmed = false,

            PasswordHash = passwordHash,
            SecurityStamp = Guid.NewGuid().ToString(),

            LockoutEndAt = null,
            AccessFailedCount = 0,
            IsDeleted = false,

            // Timestamps (CreatedAt set by repository or database)
            // Id will be generated by database or repository

            // Role - set this after getting default role
            // For now, using a hardcoded Customer role GUID
            // TODO: Make this dynamic (get "Customer" role from database)
            RoleId = Guid.Empty
        };

        // ===== STEP 4: ASSIGN DEFAULT ROLE =====

        // Use the repository instead of _context
        var customerRole = await _roleRepository.GetByNameAsync("customer");

        if (customerRole == null)
        {
            throw new InvalidOperationException("Default Customer role not found in database");
        }

        user.RoleId = customerRole.Id;

        // ===== STEP 5: SAVE USER TO DATABASE =====

        await _userRepository.AddAsync(user);
 

        var accessToken = _tokenService.GenerateAccessToken(user);

        var refreshTokenString = _tokenService.GenerateRefreshToken();

        var refreshToken = new ShoeEcommerce.Domain.Entities.RefreshToken
        {
            UserId = user.Id,
            Token = refreshTokenString,
            ExpiresAt = DateTime.UtcNow.AddDays(7),
            CreatedByIp = command.IpAddress,
            SecurityStamp = user.SecurityStamp
        };

        await _refreshTokenRepository.AddAsync(refreshToken);

        // ===== SEND CONFIRMATION EMAIL (Optional) =====

        // TODO: Implement email confirmation
        // await _emailService.SendConfirmationEmailAsync(user.Email, confirmationToken);

        // ===== STEP 8: RETURN RESPONSE =====

        return new AuthResponse
        {
            AccessToken = accessToken,
            RefreshToken = refreshTokenString,
            TokenType = "Bearer",
            ExpiresIn = _tokenService.GetAccessTokenExpirySeconds(),
            User = new UserDto
            {
                Id = user.Id,
                Email = user.Email,
                FullName = user.FullName,
                Username = user.Username,
                Role = user.Role.Name,
                EmailConfirmed = user.EmailConfirmed,
                PhoneNumberConfirmed = user.PhoneNumberConfirmed,
                PhoneNumber = user.PhoneNumber,
                CreatedAt = user.CreatedAt
            }
        };
    }
}